### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/myaccount#224]
All the things that must be done or checked when we launch, just sort of a grab bag of things we need to think of before we go live:

- [x] Ensure Matomo is receiving traffic
- [x] Make sure logging is operating as expected
- [x] Test in various browsers on Windows and macOS as well as on Android and iOS devices
- [x] Review with server team?
- [x] Decide if any messaging/communication needs to happen/do that communication (Ruth and Binky on this)
- [x] Add more prominent feedback link
- [x] Update hold success message to reflect current hold success message
- [x] Ensure pickup locations match current pickup locations
- [x] Update links that go to the old My Account where appropriate on other UL web properties
- [x] Update hold button url on the catalog (it is a setting handled by the deploy script)

**Comment by cdmo** [comment]
Matomo is setup for prod by the way. You should be able to see it at https://analytics.libraries.psu.edu/matomo

**Comment by ruthtillman** [comment]
Ruth note to self: includes Best Bets.

**Comment by ruthtillman** [comment]
holds success message: "For placed hold(s), you will receive a library notice once items are available for pick up. On-shelf items generally arrive within 2-3 weekdays. Items checked out to other borrowers will be recalled. Recalled items take a minimum of 10 days to arrive at your pick up location."

**Comment by ruthtillman** [comment]
@ruthtillman will get in touch with Chris H re: holds success message "For placed hold(s), you will receive a library notice once items are available for pick up. On-shelf items generally arrive within 2-3 weekdays. Items checked out to other borrowers will be recalled. Recalled items take a minimum of 10 days to arrive at your pick up location." because not doing recalls
